/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IToken__factory } from "./IToken__factory";
export { SimpleLudo__factory } from "./SimpleLudo__factory";
