/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IToken } from "./IToken";
export type { SimpleLudo } from "./SimpleLudo";
export * as factories from "./factories";
export { IToken__factory } from "./factories/IToken__factory";
export { SimpleLudo__factory } from "./factories/SimpleLudo__factory";
